In [ ]:
!pip install pandas

In [43]:


# ordinal encode the breast cancer dataset
from pandas import read_csv
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [5]:
# define the location of the dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv"
# load the dataset
dataset = read_csv(url, header=None)
dataset.shape


(286, 10)

In [6]:
dataset.head()

0          1        2      3      4    5        6           7      8  \
0  '40-49'  'premeno'  '15-19'  '0-2'  'yes'  '3'  'right'   'left_up'   'no'   
1  '50-59'     'ge40'  '15-19'  '0-2'   'no'  '1'  'right'   'central'   'no'   
2  '50-59'     'ge40'  '35-39'  '0-2'   'no'  '2'   'left'  'left_low'   'no'   
3  '40-49'  'premeno'  '35-39'  '0-2'  'yes'  '3'  'right'  'left_low'  'yes'   
4  '40-49'  'premeno'  '30-34'  '3-5'  'yes'  '2'   'left'  'right_up'   'no'   

                        9  
0     'recurrence-events'  
1  'no-recurrence-events'  
2     'recurrence-events'  
3  'no-recurrence-events'  
4     'recurrence-events'

In [8]:
dataset.describe()

0          1        2      3     4    5       6           7  \
count       286        286      286    286   278  286     286         285   
unique        6          3       11      7     2    3       2           5   
top     '50-59'  'premeno'  '30-34'  '0-2'  'no'  '2'  'left'  'left_low'   
freq         96        150       60    213   222  130     152         110   

           8                       9  
count    286                     286  
unique     2                       2  
top     'no'  'no-recurrence-events'  
freq     218                     201

In [9]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       286 non-null    object
 1   1       286 non-null    object
 2   2       286 non-null    object
 3   3       286 non-null    object
 4   4       278 non-null    object
 5   5       286 non-null    object
 6   6       286 non-null    object
 7   7       285 non-null    object
 8   8       286 non-null    object
 9   9       286 non-null    object
dtypes: object(10)
memory usage: 22.5+ KB


In [27]:
type(dataset)

pandas.core.frame.DataFrame

In [28]:
dataset.head(2)

0          1        2      3      4    5        6          7     8  \
0  '40-49'  'premeno'  '15-19'  '0-2'  'yes'  '3'  'right'  'left_up'  'no'   
1  '50-59'     'ge40'  '15-19'  '0-2'   'no'  '1'  'right'  'central'  'no'   

                        9  
0     'recurrence-events'  
1  'no-recurrence-events'

In [26]:
dataset.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [32]:
dataset[0].value_counts()

'50-59'    96
'40-49'    90
'60-69'    57
'30-39'    36
'70-79'     6
'20-29'     1
Name: 0, dtype: int64

In [48]:
dataset.isnull().sum()

0    0
1    0
2    0
3    0
4    8
5    0
6    0
7    1
8    0
9    0
dtype: int64

In [51]:
dataset = dataset.fillna(0)

In [52]:
dataset.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [53]:
# retrieve the array of data
data = dataset.values
# separate into input and output columns
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)


In [54]:
type(data), data[0]

(numpy.ndarray,
 array(["'40-49'", "'premeno'", "'15-19'", "'0-2'", "'yes'", "'3'",
        "'right'", "'left_up'", "'no'", "'recurrence-events'"],
       dtype=object))

In [23]:
# ordinal encode input variables
ordinal_encoder = OrdinalEncoder()
X = ordinal_encoder.fit_transform(X)
X.shape

(286, 9)

In [40]:
# ordinal encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y.shape, 

((286,),)

In [41]:
np.unique(y)

array([0, 1], dtype=int64)

In [25]:
# summarize the transformed data
print('Input', X.shape)
print(X[:5, :])
print('Output', y.shape)
print(y[:5])

Input (286, 9)
[[2. 2. 2. 0. 1. 2. 1. 2. 0.]
 [3. 0. 2. 0. 0. 0. 1. 0. 0.]
 [3. 0. 6. 0. 0. 1. 0. 1. 0.]
 [2. 2. 6. 0. 1. 2. 1. 1. 1.]
 [2. 2. 5. 4. 1. 1. 0. 4. 0.]]
Output (286,)
[1 0 1 0 1]


Training Code

In [55]:
data = dataset.values
X = data[:,:-1].astype(str)
y = data[:,-1].astype(str)
X.shape, y.shape

((286, 9), (286,))

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [58]:
X_train.shape, y_train.shape

((228, 9), (228,))

In [59]:
ord_enc = OrdinalEncoder()
ord_enc.fit(X_train)
X_train = ord_enc.transform(X_train)
X_test = ord_enc.transform(X_test)

ValueError: Found unknown categories ['-1'] in column 7 during transform