In [24]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder, LabelBinarizer

In [11]:
data = asarray([['red'], ['green'], ['blue']])
data, type(data), data.shape

(array([['red'],
        ['green'],
        ['blue']], dtype='<U5'),
 numpy.ndarray,
 (3, 1))

In [ ]:
help(LabelBinarizer)

In [26]:
LB = LabelBinarizer()
LB.fit_transform(['red', 'green', 'blue'])


array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [23]:
LE = LabelEncoder()
le_data = LE.fit_transform(['red', 'green', 'blue'])
le_data

array([2, 1, 0], dtype=int64)

In [16]:
OE = OrdinalEncoder()
t_data = OE.fit_transform(data)
t_data

array([[2.],
       [1.],
       [0.]])

In [20]:
OHE = OneHotEncoder(categories=[sparse=False, drop='first')
ohe_data = OHE.fit_transform(data)
ohe_data

array([[0., 1.],
       [1., 0.],
       [0., 0.]])

In [18]:
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing._encoders:

class OneHotEncoder(_BaseEncoder)
 |  OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')
 |  
 |  Encode categorical features as a one-hot numeric array.
 |  
 |  The input to this transformer should be an array-like of integers or
 |  strings, denoting the values taken on by categorical (discrete) features.
 |  The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
 |  encoding scheme. This creates a binary column for each category and
 |  returns a sparse matrix or dense array (depending on the ``sparse``
 |  parameter)
 |  
 |  By default, the encoder derives the categories based on the unique values
 |  in each feature. Alternatively, you can also specify the `categories`
 |  manually.
 |  
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard ker